### ISSUE TITLE
VirusTotal detects the exe as a virus

### ISSUE THREAD

**Issue by BardockShiny** [Haruki1707/ShortCutes#7]
Cyren: W32/MSIL_Kryptik.EHH.gen!Eldorado
Fortinet: PossibleThreat
Google: Detected
MaxSecure :Trojan.Malware.300983.susgen
McAfee :PWS-FCSU!290264AB42FC
McAfee-GW-Edition :PWS-FCSU!290264AB42FC
Palo Alto :NetworksGeneric.ml
SecureAge :Malicious
TrendMicro-HouseCall: TROJ_GEN.R002H06DP23

**Comment by Haruki1707** [comment]
Yeah, that is a false positive.

It detects it as a virus because it generates compiled programs at runtime (the game launcher). Some viruses are known to remain dormant on your PC until they compile malicious DLL or EXE files. Additionally, not having the funds to digitally sign ShortCutes as a trusted program causes many anti-virus software to flag it as a virus.

I can guarantee you that it doesn't contain any viruses, but it's understandable if you decide not to use it.
